### ISSUE TITLE
V0.9.0 (Stable) shows no libraries available

### ISSUE THREAD

**Issue by tiny-e** [PlexRipper/PlexRipper#134]
Sees my account/servers, but doesn't show any available libraries.

<details><summary>Click to show log</summary>

```text  error  warn  system  array  login  


12:00:03 [Debug] [AddOrUpdatePlexServersCommandHandler.Handle] => PlexAccount MYACCOUNT already has an association with PlexServer: FRIEND ACCOUNT, updating authentication token now.

12:00:03 [Information] [AddOrUpdatePlexServersCommandHandler.Handle] => Removing PlexAccount associations with PlexServers now that are not accessible anymore

12:00:03 [Information] [PlexAccountService.SetupAccountAsync] => Account was setup successfully!: 

12:00:03 [Debug] [InspectPlexServersJob.Execute] => Executing job: InspectPlexServersJob for plexAccountId: 1

12:00:03 [Information] [PlexServerService.InspectPlexServers] => Inspecting 3 PlexServers for PlexAccount: MYACCOUNT

12:00:13 [Warning] [PlexApiClient.SendRequestAsync] => Waiting 1 seconds before retrying again.

12:00:13 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:13 [Warning] [PlexApiClient.SendRequestAsync] => Waiting 1 seconds before retrying again.

12:00:13 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Response URI:  - (0)

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Message: The request timed-out.

12:00:13 [Warning] [PlexApiClient.SendRequestAsync] => Waiting 1 seconds before retrying again.

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Response URI:  - (0)

12:00:13 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Message: The request timed-out.

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Response URI:  - (0)

12:00:13 [Error] [PlexApiClient.SendRequestAsync] => Error Message: The request timed-out.

12:00:24 [Error] [PlexApiClient.GenerateResult] => PlexApi Error: Error on request to  (0) - : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => PlexApi Error: Error on request to  (0) - : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => StatusCode - 0: 

12:00:24 [Error] [PlexApiClient.GenerateResult] => PlexApi Error: Error on request to  (0) - : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => StatusCode - 0: 

12:00:24 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:24 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:24 [Error] [PlexApiClient.GenerateResult] => : 

12:00:24 [Error] [PlexApiClient.GenerateResult] => StatusCode - 0: 

12:00:24 [Debug] [SignalRService.SendServerInspectStatusProgress] => InspectServerProgress => PlexRipper.Application.Common.WebApi.InspectServerProgress

12:00:24 [Error] Job SyncGroup.SetupAccountJobKey threw an unhandled Exception: 
System.Collections.Generic.KeyNotFoundException: The given key 'StatusCode' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PlexRipper.PlexApi.Api.PlexApi.GetServerStatusAsync(String authToken, String serverBaseUrl, Action`1 action) in /src/src/PlexApi/Api/PlexApi.cs:line 88
   at PlexRipper.Application.PlexServers.PlexServerService.CheckPlexServerStatusAsync(PlexServer plexServer, Int32 plexAccountId, Boolean trimEntries, Action`1 progressAction) in /src/src/Application/PlexServers/PlexServerService.cs:line 336
   at PlexRipper.Application.PlexServers.PlexServerService.<>c__DisplayClass12_0.<<InspectPlexServers>b__0>d.MoveNext() in /src/src/Application/PlexServers/PlexServerService.cs:line 248
--- End of stack trace from previous location ---
   at PlexRipper.Application.PlexServers.PlexServerService.InspectPlexServers(Int32 plexAccountId) in /src/src/Application/PlexServers/PlexServerService.cs:line 301
   at PlexRipper.Application.InspectPlexServersJob.Execute(IJobExecutionContext context) in /src/src/Application/Scheduler/Jobs/InspectPlexServersJob.cs:line 22
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)

12:00:24 [Error] Job SyncGroup.SetupAccountJobKey threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception.
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'StatusCode' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PlexRipper.PlexApi.Api.PlexApi.GetServerStatusAsync(String authToken, String serverBaseUrl, Action`1 action) in /src/src/PlexApi/Api/PlexApi.cs:line 88
   at PlexRipper.Application.PlexServers.PlexServerService.CheckPlexServerStatusAsync(PlexServer plexServer, Int32 plexAccountId, Boolean trimEntries, Action`1 progressAction) in /src/src/Application/PlexServers/PlexServerService.cs:line 336
   at PlexRipper.Application.PlexServers.PlexServerService.<>c__DisplayClass12_0.<<InspectPlexServers>b__0>d.MoveNext() in /src/src/Application/PlexServers/PlexServerService.cs:line 248
--- End of stack trace from previous location ---
   at PlexRipper.Application.PlexServers.PlexServerService.InspectPlexServers(Int32 plexAccountId) in /src/src/Application/PlexServers/PlexServerService.cs:line 301
   at PlexRipper.Application.InspectPlexServersJob.Execute(IJobExecutionContext context) in /src/src/Application/Scheduler/Jobs/InspectPlexServersJob.cs:line 22
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.Collections.Generic.KeyNotFoundException: The given key 'StatusCode' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PlexRipper.PlexApi.Api.PlexApi.GetServerStatusAsync(String authToken, String serverBaseUrl, Action`1 action) in /src/src/PlexApi/Api/PlexApi.cs:line 88
   at PlexRipper.Application.PlexServers.PlexServerService.CheckPlexServerStatusAsync(PlexServer plexServer, Int32 plexAccountId, Boolean trimEntries, Action`1 progressAction) in /src/src/Application/PlexServers/PlexServerService.cs:line 336
   at PlexRipper.Application.PlexServers.PlexServerService.<>c__DisplayClass12_0.<<InspectPlexServers>b__0>d.MoveNext() in /src/src/Application/PlexServers/PlexServerService.cs:line 248
--- End of stack trace from previous location ---
   at PlexRipper.Application.PlexServers.PlexServerService.InspectPlexServers(Int32 plexAccountId) in /src/src/Application/PlexServers/PlexServerService.cs:line 301
   at PlexRipper.Application.InspectPlexServersJob.Execute(IJobExecutionContext context) in /src/src/Application/Scheduler/Jobs/InspectPlexServersJob.cs:line 22
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
```
</details>

**Comment by JasonLandbridge** [comment]
Hi there, I think this has been fixed in the latest v0.9.0 release. Can you give it a try and let me know if it is still an issue?
