### ISSUE TITLE
Error when downloading from Windows Hosted Plex Servers

### ISSUE THREAD

**Issue by Deathbot64** [PlexRipper/PlexRipper#189]
I can download stuff without on non windows hosted servers but I keep getting this path error when trying to download from windows server

`01:46:59 [Error] [FileSystem.Create] => --Could not find a part of the path '/Downloads/Movies/A Muppet Family Christmas (1987)/E:\Library\Movies\A Muppet Family Christmas.part1.mp4'. - System.Private.CoreLib:`

**Comment by JasonLandbridge** [comment]
Hi, 

Did you select a folder for the downloads in the settings?

**Comment by Deathbot64** [comment]
Yes I did

**Comment by JasonLandbridge** [comment]
Thanks for confirming, can you send plexripper@protonmail.com an email with your email so I can follow up?

**Comment by Deathbot64** [comment]
any updates on this issue?

**Comment by JasonLandbridge** [comment]
Hey unfortunately not, I've just created a new big release but haven't worked on this issue. I also don't have a windows hosted Plex server I can use to test with. If you have an account available with such access, please send those login details to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) and then I can work on it

**Comment by Deathbot64** [comment]
I just sent you an invite to use my server, The Archive. Same user name. 

https://clients.plex.tv/servers/shared_servers/accept?invite_token=4RZTz87HMCgyizZ4SS-y

Link to the invite just incase.

**Comment by JasonLandbridge** [comment]
Hey thanks for the quick reply, I have some throw away accounts for testing purposes. Could you send an e-mail to [plexripper@protonmail.com](mailto:plexripper@protonmail.com) and then I will reply back with the throw-away email. Thanks!

**Comment by TheTrustedAdvisor** [comment]
Any news here? Still not working on my side ...

**Comment by JasonLandbridge** [comment]
@mfalland Post some paths that are not working and then I can take a look

**Comment by TheTrustedAdvisor** [comment]
11:51:36 [Error] [DownloadFileStream.CreateDownloadFileStream:66] => Invalid argument : '/Downloads/Movies/2 Fast 2 Furious/E:\Movies\2 Fast 2 Furious (2003)\2 Fast 2 Furious (2003) Remux-1080p Proper.part4.mkv'
System.IO.IOException: Invalid argument : '/Downloads/Movies/2 Fast 2 Furious/E:\Movies\2 Fast 2 Furious (2003)\2 Fast 2 Furious (2003) Remux-1080p Proper.part4.mkv'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.Create(String path, Int32 bufferSize, FileOptions options)
   at System.IO.Abstractions.FileWrapper.Create(String path, Int32 bufferSize, FileOptions options)
   at PlexRipper.FileSystem.FileSystem.Create(String path, Int32 bufferSize, FileOptions options) in /src/src/FileSystem/FileSystem.cs:line 61

11:51:36 [Error] [DownloadWorker.SendDownloadWorkerError:265] => Could not create a download destination filestream for DownloadWorker with id 68

**Comment by JasonLandbridge** [comment]
This has been fixed in the latest stable release
