### ISSUE TITLE
Error [FileSystem.Create:72] when downloading TvShows

### ISSUE THREAD

**Issue by Markovski2338** [PlexRipper/PlexRipper#251]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

latest

### Platform

Windows

### Browsers

Microsoft Edge (LOL)

### Description

TvShows are not downloaded completely. It says that download has completed  but only 273kb of data out of 2.4Gb has been received. 

### Reproduction steps

```bash
Error happens when you try to download a TvShow.
```

### Screenshots

```bash
![Screenshot 2023-07-26 211417](https://github.com/PlexRipper/PlexRipper/assets/140672753/c12c7451-d152-4171-8a86-15b28d954a53)
```

### Logs

```bash
2023-07-26 21:05:43 01:05:43 [Debug] [DownloadController.DownloadMedia:75] => Attempting to add download task orders: 
2023-07-26 21:05:43 
2023-07-26 21:05:43 01:05:43 [Debug] [DownloadController.DownloadMedia:77] => DownloadMediaDTO: {"MediaIds": [26427], "Type": "Episode", "PlexServerId": 2, "PlexLibraryId": 12, "$type": "DownloadMediaDTO"} 
2023-07-26 21:05:43 
2023-07-26 21:05:43 01:05:43 [Debug] [DownloadTaskValidator.ValidateDownloadTasks:84] => Validating DownloadTask 1 of 1 with title Star Trek: Strange New Worlds
2023-07-26 21:05:43 
2023-07-26 21:05:43 01:05:43 [Debug] [DownloadTaskValidator.ValidateDownloadTasks:97] => DownloadTask 1 of 1 with title Star Trek: Strange New Worlds was valid
2023-07-26 21:05:43 
2023-07-26 21:05:43 01:05:43 [Information] [DownloadTaskValidator.ValidateDownloadTasks:113] => All 1 downloadTasks passed validation!
2023-07-26 21:05:44 
2023-07-26 21:05:44 01:05:44 [Debug] [DownloadCommands.CreateDownloadTasks:66] => Successfully added all 1 DownloadTasks
2023-07-26 21:05:44 
2023-07-26 21:05:44 01:05:44 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Star Trek: Strange New Worlds/Season 2/The Broken Circle to start as the next task
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadJob.Execute:63] => Executing job: DownloadJob for downloadTaskId with id: 8
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadJob.Execute:80] => Creating Download client for Star Trek: Strange New Worlds/Season 2/The Broken Circle
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadJob.Execute:108] => Generated DownloadWorkerTasks for Star Trek: Strange New Worlds/Season 2/The Broken Circle
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [PlexDownloadClient.Start:117] => Start downloading Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadWorker.Start:108] => Download worker with id: 11 start for filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 11 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to Downloading
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 11 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to DownloadFinished
2023-07-26 21:05:45 
2023-07-26 21:05:45 01:05:45 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 11 with Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv finished!
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:217] => [File: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv - Status: DownloadFinished] - (11 - 0 ) = ( - 0)
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Debug] [FileMergeScheduler.CreateFileTaskFromDownloadTask:33] => Adding DownloadTask The Broken Circle with id 8 to a FileTask to be merged
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Debug] [DownloadJob.Execute:141] => Exiting job: DownloadJob for DownloadTask with id: 8
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Star Trek: Strange New Worlds/Season 2/The Broken Circle to start as the next task
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Debug] [FileMergeJob.Execute:51] => Executing job: FileMergeJob for fileTaskId with id: 6
2023-07-26 21:05:47 
2023-07-26 21:05:47 01:05:47 [Information] [FileMergeJob.Execute:68] => Executing FileMergeJob with name Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv and id 6
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [FileMergeJob.Execute:115] => Starting file merge process for 1 parts into a file Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Warning] [DownloadJob.Dispose:152] => Disposing job: DownloadJob for DownloadTask
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Warning] [PlexDownloadClient.DisposeAsync:170] => PlexDownloadClient for DownloadTask with Id: 8 was disposed
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadJob.Execute:63] => Executing job: DownloadJob for downloadTaskId with id: 8
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadJob.Execute:80] => Creating Download client for Star Trek: Strange New Worlds/Season 2/The Broken Circle
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [PlexDownloadClient.Start:117] => Start downloading Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadWorker.Start:108] => Download worker with id: 11 start for filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 11 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to Downloading
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 11 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to DownloadFinished
2023-07-26 21:05:48 
2023-07-26 21:05:48 01:05:48 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 11 with Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv finished!
2023-07-26 21:05:49 
2023-07-26 21:05:49 01:05:49 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:217] => [File: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv - Status: DownloadFinished] - (11 - 0 ) = ( - 0)
2023-07-26 21:05:49 
2023-07-26 21:05:49 01:05:49 [Debug] [FileMergeScheduler.CreateFileTaskFromDownloadTask:33] => Adding DownloadTask The Broken Circle with id 8 to a FileTask to be merged
2023-07-26 21:05:53 
2023-07-26 21:05:53 01:05:53 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download
2023-07-26 21:05:54 
2023-07-26 21:05:54 01:05:54 [Debug] [DownloadJob.Execute:141] => Exiting job: DownloadJob for DownloadTask with id: 8
2023-07-26 21:05:54 
2023-07-26 21:05:54 01:05:54 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start
2023-07-26 21:05:54 
2023-07-26 21:05:54 01:05:54 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Star Trek: Strange New Worlds/Season 2/The Broken Circle to start as the next task
2023-07-26 21:05:55 
2023-07-26 21:05:55 01:05:55 [Debug] [FileMergeJob.Execute:51] => Executing job: FileMergeJob for fileTaskId with id: 7
2023-07-26 21:05:55 
2023-07-26 21:05:55 01:05:55 [Information] [FileMergeJob.Execute:68] => Executing FileMergeJob with name Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv and id 7
2023-07-26 21:05:55 
2023-07-26 21:05:55 01:05:55 [Warning] [DownloadTaskScheduler.StartDownloadTaskJob:31] => DownloadJob with DownloadJob.DownloadTaskId_8 already exists
2023-07-26 21:05:56 
2023-07-26 21:05:56 01:05:56 [Error] [FileSystem.Create:72] => The process cannot access the file '/TvShows/Star Trek Strange New Worlds/Season 2/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv' because it is being used by another process.
2023-07-26 21:05:56 System.IO.IOException: The process cannot access the file '/TvShows/Star Trek Strange New Worlds/Season 2/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv' because it is being used by another process.
2023-07-26 21:05:56    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
2023-07-26 21:05:56    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
2023-07-26 21:05:56    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
2023-07-26 21:05:56    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2023-07-26 21:05:56    at System.IO.File.Create(String path, Int32 bufferSize, FileOptions options)
2023-07-26 21:05:56    at System.IO.Abstractions.FileWrapper.Create(String path, Int32 bufferSize, FileOptions options)
2023-07-26 21:05:56    at PlexRipper.FileSystem.FileSystem.Create(String path, Int32 bufferSize, FileOptions options) in /src/src/FileSystem/FileSystem.cs:line 67
2023-07-26 21:05:56 
2023-07-26 21:05:56 01:05:56 [Error] [FileMergeJob.Execute:106] => The process cannot access the file '/TvShows/Star Trek Strange New Worlds/Season 2/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv' because it is being used by another process.
2023-07-26 21:05:56 System.IO.IOException: The process cannot access the file '/TvShows/Star Trek Strange New Worlds/Season 2/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv' because it is being used by another process.
2023-07-26 21:05:56    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Int64& fileLength, UnixFileMode& filePermissions)
2023-07-26 21:05:56    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
2023-07-26 21:05:56    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
2023-07-26 21:05:56    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
2023-07-26 21:05:56    at System.IO.File.Create(String path, Int32 bufferSize, FileOptions options)
2023-07-26 21:05:56    at System.IO.Abstractions.FileWrapper.Create(String path, Int32 bufferSize, FileOptions options)
2023-07-26 21:05:56    at PlexRipper.FileSystem.FileSystem.Create(String path, Int32 bufferSize, FileOptions options) in /src/src/FileSystem/FileSystem.cs:line 67
2023-07-26 21:05:57 
2023-07-26 21:05:57 01:05:57 [Warning] [DownloadJob.Dispose:152] => Disposing job: DownloadJob for DownloadTask
2023-07-26 21:05:57 
2023-07-26 21:05:57 01:05:57 [Warning] [PlexDownloadClient.DisposeAsync:170] => PlexDownloadClient for DownloadTask with Id: 8 was disposed
2023-07-26 21:06:01 
2023-07-26 21:06:01 01:06:01 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/TvShows/Star Trek Strange New Worlds/Season 2/The Broken Circle/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv has been merged into the single media file
2023-07-26 21:06:01 
2023-07-26 21:06:01 01:06:01 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/TvShows/Star Trek Strange New Worlds/Season 2/The Broken Circle/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv since it has been merged already
2023-07-26 21:06:03 
2023-07-26 21:06:03 01:06:03 [Information] [FileMergeJob.Execute:133] => Finished combining 1 files into Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
```

**Comment by martin-polanski** [comment]
I have tried to download the same file again, and it still has the same issue, except that the logs dont show the FileSystem error this time.... 

2023-07-26 21:38:14 01:38:14 [Debug] [DownloadController.DownloadMedia:75] => Attempting to add download task orders: 
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadController.DownloadMedia:77] => DownloadMediaDTO: {"MediaIds": [26427], "Type": "Episode", "PlexServerId": 2, "PlexLibraryId": 12, "$type": "DownloadMediaDTO"} 
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadTaskValidator.ValidateDownloadTasks:84] => Validating DownloadTask 1 of 1 with title Star Trek: Strange New Worlds
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadTaskValidator.ValidateDownloadTasks:97] => DownloadTask 1 of 1 with title Star Trek: Strange New Worlds was valid
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Information] [DownloadTaskValidator.ValidateDownloadTasks:113] => All 1 downloadTasks passed validation!
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadCommands.CreateDownloadTasks:66] => Successfully added all 1 DownloadTasks
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Star Trek: Strange New Worlds/Season 2/The Broken Circle to start as the next task
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadJob.Execute:63] => Executing job: DownloadJob for downloadTaskId with id: 11
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadJob.Execute:80] => Creating Download client for Star Trek: Strange New Worlds/Season 2/The Broken Circle
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadJob.Execute:108] => Generated DownloadWorkerTasks for Star Trek: Strange New Worlds/Season 2/The Broken Circle
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [PlexDownloadClient.Start:117] => Start downloading Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadWorker.Start:108] => Download worker with id: 12 start for filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadWorker.DownloadProcessAsync:166] => Downloading from url: ***MASKED***
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 12 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to Downloading
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Debug] [DownloadWorker.SetDownloadWorkerTaskChanged:293] => Download worker with id: 12 and with filename: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv changed status to DownloadFinished
2023-07-26 21:38:14 
2023-07-26 21:38:14 01:38:14 [Information] [DownloadWorker.SendDownloadFinished:268] => Download worker 12 with Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv finished!
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Debug] [PlexDownloadClient.OnDownloadWorkerTaskUpdate:217] => [File: Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv - Status: DownloadFinished] - (12 - 0 ) = ( - 0)
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Debug] [FileMergeScheduler.CreateFileTaskFromDownloadTask:33] => Adding DownloadTask The Broken Circle with id 11 to a FileTask to be merged
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Information] [DownloadQueue.CheckDownloadQueue:61] => Adding 1 PlexServers to the DownloadQueue to check for the next download
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Debug] [DownloadJob.Execute:141] => Exiting job: DownloadJob for DownloadTask with id: 11
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Debug] [DownloadQueue.CheckDownloadQueueServer:83] => Checking PlexServer: ***MASKED*** for the next download to start
2023-07-26 21:38:15 
2023-07-26 21:38:15 01:38:15 [Information] [DownloadQueue.CheckDownloadQueueServer:94] => Selected download task Star Trek: Strange New Worlds/Season 2/The Broken Circle to start as the next task
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Debug] [FileMergeJob.Execute:51] => Executing job: FileMergeJob for fileTaskId with id: 8
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Information] [FileMergeJob.Execute:68] => Executing FileMergeJob with name Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv and id 8
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Warning] [DownloadTaskScheduler.StartDownloadTaskJob:31] => DownloadJob with DownloadJob.DownloadTaskId_11 already exists
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Debug] [FileMergeJob.Execute:115] => Starting file merge process for 1 parts into a file Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Warning] [DownloadJob.Dispose:152] => Disposing job: DownloadJob for DownloadTask
2023-07-26 21:38:16 
2023-07-26 21:38:16 01:38:16 [Warning] [PlexDownloadClient.DisposeAsync:170] => PlexDownloadClient for DownloadTask with Id: 11 was disposed
2023-07-26 21:38:21 
2023-07-26 21:38:21 01:38:21 [Debug] [FileMergeStreamProvider.MergeFiles:70] => The file at /Downloads/TvShows/Star Trek Strange New Worlds/Season 2/The Broken Circle/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv has been merged into the single media file
2023-07-26 21:38:21 
2023-07-26 21:38:21 01:38:21 [Debug] [FileMergeStreamProvider.MergeFiles:71] => Deleting file /Downloads/TvShows/Star Trek Strange New Worlds/Season 2/The Broken Circle/Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.part1.mkv since it has been merged already
2023-07-26 21:38:21 
2023-07-26 21:38:21 01:38:21 [Information] [FileMergeJob.Execute:133] => Finished combining 1 files into Star Trek Strange New Worlds.s02e01.The Broken Circle.1080p.mkv

**Comment by JasonLandbridge** [comment]
Due to the age of this issue I'm closing it as a big update ([0.15-0.17](https://github.com/PlexRipper/PlexRipper/releases)) with a years worth of updates and fixes has been released. Please let me know if this is still an issue!
