### ISSUE TITLE
[BUG] - Fails to authenticate with Plex.

### ISSUE THREAD

**Issue by kdegeek** [PlexRipper/PlexRipper#285]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

Latest

### Platform

Mac

### Browsers

Firefox, Safari (Yeah good luck with that...)

### Description

Upon setup, everything works beautifully. Until I attempt to add my account. 

I have tried removing 2-factor, and that doesn't help. Tried with email instead of username. Tried with 2 browsers. Tried nuking the container, clearing the DB and config, then re-running it. Nothing seems to work

For the record. I friggin love the work you put into this. Gorgeous work!

### Reproduction steps

```bash
1. Download container
2. Run container with proper variables
3. Attempt to add flex account on setup
4. Validation doesn't allow saving
5. Check logs
6. Swear mightily 
7. Repeat
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
2023-12-29 11:54:29 
2023-12-29 11:54:29 17:54:29 [Information] [PlexRipperHost.Setup:18] => Currently running on Linux
2023-12-29 11:54:29 
2023-12-29 11:54:29 17:54:29 [Information] [PlexRipperDbContext.Setup:173] => Setting up the PlexRipper database
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [PlexRipperDbContext.Setup:179] => Attempting to migrate database
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [PlexRipperDbContext.Setup:196] => Database was successfully connected!
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [PlexRipperDbContext.Setup:197] => Database connected at: /Config/PlexRipperDB.db
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Startup..ctor:20] => PlexRipper running in Production mode
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Debug] [PlexRipperHost.Setup:31] => Setting up Autofac Containers
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.DBConnectionManager:0] => Registering datasource 'default' with db provider: 'Quartz.Impl.AdoJobStore.Common.DbProvider'
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.StdSchedulerFactory:0] => Using object serializer: Quartz.Simpl.JsonObjectSerializer, Quartz.Serialization.Json
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.StdSchedulerFactory:0] => Using custom data access locking (synchronization): Quartz.Impl.AdoJobStore.UpdateLockRowSemaphore
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.SchedulerSignalerImpl:0] => Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.QuartzScheduler:0] => Quartz Scheduler created
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.QuartzScheduler:0] => JobFactory set to: Autofac.Extras.Quartz.AutofacJobFactory
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => With SQLite we need to set AcquireTriggersWithinLock to true, changing
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Detected usage of SQLiteDelegate - defaulting 'txIsolationLevelSerializable' to 'true'
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Successfully validated presence of 10 schema objects
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => JobStoreTX initialized.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.StdSchedulerFactory:0] => Quartz Scheduler 3.5.0.0 - 'PlexRipper Scheduler' with instanceId 'NON_CLUSTERED' initialized
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.StdSchedulerFactory:0] => Using thread pool 'Quartz.Simpl.DefaultThreadPool', size: 10
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.StdSchedulerFactory:0] => Using job store 'Quartz.Impl.AdoJobStore.JobStoreTX', supports persistence: True, clustered: False
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Boot.WaitForStartAsync:55] => Initiating boot process
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [ConfigManager.Setup:44] => Checking if PlexRipperSettings.json exists at /Config
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [ConfigManager.Setup:51] => Config directory exists, will use /Config
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [ConfigManager.Setup:67] => PlexRipperSettings.json doesn't exist, will create new one now in /Config
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [ConfigManager.SaveConfig:120] => Saving user config settings now
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [ConfigManager.SaveConfig:130] => UserSettings were saved successfully!
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Debug] [SchedulerService.SetupListeners:61] => Setting up Quartz listeners
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [SchedulerService.SetupAsync:42] => Starting Quartz Scheduler
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Freed 0 triggers from 'acquired' / 'blocked' state.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Recovering 0 jobs that were in-progress at the time of the last shut-down.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Recovery complete.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Removed 0 'complete' triggers.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.JobStoreTX:0] => Removed 0 stale fired job entries.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Quartz.QuartzScheduler:0] => Scheduler PlexRipper Scheduler_$_NON_CLUSTERED started.
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Information] [Boot.WaitForStartAsync:66] => Finished Initiating boot process
2023-12-29 11:54:30 
2023-12-29 11:54:30 17:54:30 [Warning] [Microsoft.FileSystemXmlRepository:0] => Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
2023-12-29 11:54:31 
2023-12-29 11:54:31 17:54:31 [Warning] [Microsoft.XmlKeyManager:0] => No XML encryptor configured. Key {1da1e8ce-6f8c-4b1d-8921-ffd00e5e4378} may be persisted to storage in unencrypted form.
2023-12-29 11:54:31 
2023-12-29 11:54:31 17:54:31 [Information] [Microsoft.Lifetime:0] => Now listening on: http://[::]:7000
2023-12-29 11:54:31 
2023-12-29 11:54:31 17:54:31 [Information] [Boot.OnStarted:75] => Boot.OnStarted has been called
2023-12-29 11:57:45 
2023-12-29 11:57:45 17:57:45 [Debug] [PlexAccountService.GetAllPlexAccountsAsync:172] => Returning all PlexAccounts
2023-12-29 11:57:45 
2023-12-29 11:57:45 17:57:45 [Debug] [PlexAccountController.GetAllAccounts:38] => Returned 0 accounts
2023-12-29 11:58:22 
2023-12-29 11:58:22 17:58:22 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
2023-12-29 11:58:22 
2023-12-29 11:58:22 17:58:22 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
2023-12-29 11:58:23 
2023-12-29 11:58:23 17:58:23 [Debug] [RestSharpExtensions.ToResponseResult:92] => 
2023-12-29 11:58:23  - Metadata:
2023-12-29 11:58:23  -- StatusCode - 201
2023-12-29 11:58:23 
2023-12-29 11:58:23 17:58:23 [Error] [Microsoft.Kestrel:0] => Connection id "0HN08IUK6LESV", Request id "0HN08IUK6LESV:00000010": An unhandled exception was thrown by the application.
2023-12-29 11:58:23 System.NullReferenceException: Object reference not set to an instance of an object.
2023-12-29 11:58:23    at PlexRipper.PlexApi.Services.PlexApiService.PlexSignInAsync(PlexAccount plexAccount) in /src/src/PlexApi/Services/PlexApiService.cs:line 283
2023-12-29 11:58:23    at PlexRipper.Application.PlexAccounts.PlexAccountService.ValidatePlexAccountAsync(PlexAccount plexAccount) in /src/src/Application/PlexAccounts/PlexAccountService.cs:line 49
2023-12-29 11:58:23    at PlexRipper.WebAPI.Controllers.PlexAccountController.Validate(PlexAccountDTO account) in /src/src/WebAPI/Controllers/PlexAccountController.cs:line 108
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2023-12-29 11:58:23    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2023-12-29 11:58:23    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by kdegeek** [comment]
Pretty much anything will work in step 6, as long as it is done loudly, and with vigorous intonation 🤣

I am indeed running on M1 Apple silicon, though if you aren’t inclined to debug for that I understand- I have a KDE Neon box here I can also try it on.

I did try letting it sit and refresh the browser with little luck, though when I saw the log errors I’ll admit to not waiting as long as I likely could have lol

**Comment by kdegeek** [comment]
Interestingly, I'm getting the same error and code when installing on my Unraid server and trying to authenticate

**Comment by JasonLandbridge** [comment]
Due to the age of this issue I'm closing it as a big update ([0.15-0.17](https://github.com/PlexRipper/PlexRipper/releases)) with a years worth of updates and fixes has been released. Please let me know if this is still an issue!
