### ISSUE TITLE
[BUG] - <Cannot Authenticate>

### ISSUE THREAD

**Issue by kdegeek** [PlexRipper/PlexRipper#290]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

Latest

### Platform

Unraid

### Browsers

Firefox, Safari (Yeah good luck with that...)

### Description

I'm creating a new bug report here, because I am recreating an identical issue on an x64 Unraid system.

Steps are identical to Bug #285, but on a fresh, completely unrelated system

You will notice in the log some errors related to 2FA, I attempted turning 2FA on to see if it would get me past the errors. 

The final spate of errors shown are all with 2FA turned off. 

### Reproduction steps

```bash
Same as bug #285
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
14:54:30 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
14:54:30 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
14:54:31 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Request to https://plex.tv/api/v2/users/signin failed with status code: 401 - 

 - Metadata:
 -- StatusCode - 401
 -- ErrorMessage - No error message found
14:54:31 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Invalid verification code
14:54:33 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
14:54:33 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
14:54:34 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Request to https://plex.tv/api/v2/users/signin failed with status code: 401 - 

 - Metadata:
 -- StatusCode - 401
 -- ErrorMessage - No error message found
14:54:34 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Invalid verification code
14:55:40 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
14:55:40 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
14:55:41 [Debug] [RestSharpExtensions.ToResponseResult:92] => 

 - Metadata:
 -- StatusCode - 201
14:55:41 [Error] [Microsoft.Kestrel:0] => Connection id "0HN15PTPHSHKL", Request id "0HN15PTPHSHKL:0000001F": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRipper.PlexApi.Services.PlexApiService.PlexSignInAsync(PlexAccount plexAccount) in /src/src/PlexApi/Services/PlexApiService.cs:line 283
   at PlexRipper.Application.PlexAccounts.PlexAccountService.ValidatePlexAccountAsync(PlexAccount plexAccount) in /src/src/Application/PlexAccounts/PlexAccountService.cs:line 49
   at PlexRipper.WebAPI.Controllers.PlexAccountController.Validate(PlexAccountDTO account) in /src/src/WebAPI/Controllers/PlexAccountController.cs:line 108
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
14:55:43 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
14:55:43 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
14:55:43 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Request to https://plex.tv/api/v2/users/signin failed with status code: 401 - 

 - Metadata:
 -- StatusCode - 401
 -- ErrorMessage - No error message found
14:55:43 [Error] [RestSharpExtensions.ParsePlexErrors:159] => Invalid verification code
14:55:48 [Debug] [PlexAccountService.GetAllPlexAccountsAsync:172] => Returning all PlexAccounts
14:55:48 [Debug] [PlexAccountController.GetAllAccounts:38] => Returned 0 accounts
15:01:05 [Debug] [PlexAccountService.GetAllPlexAccountsAsync:172] => Returning all PlexAccounts
15:01:05 [Debug] [PlexAccountController.GetAllAccounts:38] => Returned 0 accounts
15:01:34 [Debug] [PlexApi.PlexSignInAsync:49] => Requesting PlexToken for account ***MASKED***
15:01:34 [Debug] [PlexApiClient.SendRequestAsync:58] => Sending request to: https://plex.tv/api/v2/users/signin?X-Plex-Product=Plex Web&X-Plex-Client-Identifier=Chrome&X-Plex-Platform=Chrome&X-Plex-Platform-Version=87.0&X-Plex-Sync-Version=2&X-Plex-Features=external-media%2cindirect-media&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1673x1297%2c2560x1440&X-Plex-Language=en
15:01:35 [Debug] [RestSharpExtensions.ToResponseResult:92] => 

 - Metadata:
 -- StatusCode - 201
15:01:35 [Error] [Microsoft.Kestrel:0] => Connection id "0HN15PTPHSHL4", Request id "0HN15PTPHSHL4:00000004": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexRipper.PlexApi.Services.PlexApiService.PlexSignInAsync(PlexAccount plexAccount) in /src/src/PlexApi/Services/PlexApiService.cs:line 283
   at PlexRipper.Application.PlexAccounts.PlexAccountService.ValidatePlexAccountAsync(PlexAccount plexAccount) in /src/src/Application/PlexAccounts/PlexAccountService.cs:line 49
   at PlexRipper.WebAPI.Controllers.PlexAccountController.Validate(PlexAccountDTO account) in /src/src/WebAPI/Controllers/PlexAccountController.cs:line 108
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by JasonLandbridge** [comment]
Due to the age of this issue I'm closing it as a big update ([0.15-0.17](https://github.com/PlexRipper/PlexRipper/releases)) with a years worth of updates and fixes has been released. Please let me know if this is still an issue!
