### ISSUE TITLE
[BUG] - <Downloads not working>

### ISSUE THREAD

**Issue by Hoopes80** [PlexRipper/PlexRipper#340]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.21.0

### Platform

Unraid

### Browsers

Google Chrome

### Description

Downloads don't work 

### Reproduction steps

```bash
1. Go to '...' server
2. Click on '....'tv show wanting to download 
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
text  error  warn  system  array  login  

      ) AS "t" ON "d"."Id" = "t"."ParentId"
      ORDER BY "d"."Id", "p"."Id", "p0"."Id", "t"."CreatedAt", "t"."Id", "t"."Id0"

13:20:02 [Error] [LogManager.DbContextLogger:36] => fail: 08/21/2024 13:20:02.382 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'PlexRipper.Data.PlexRipperDbContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

13:20:02 [Error] [Microsoft.Kestrel:0] => Connection id "0HN61TR3FPTJS", Request id "0HN61TR3FPTJS:00000003": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Data.Contracts.DbContextExtensions.GetAllDownloadTasksByServerAsync(IPlexRipperDbContext dbContext, Int32 plexServerId, Boolean asTracking, CancellationToken cancellationToken) in /src/src/Data.Contracts/Extensions/DbContext/DbContextExtensions.DownloadTasks.cs:line 223
   at PlexRipper.Application.GetAllDownloadTasksEndpoint.HandleAsync(CancellationToken ct) in /src/src/Application/PlexDownloads/GetAll/GetAllDownloadTasksEndpoint.cs:line 30
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

13:21:17 [Debug] [GetAllPlexAccountsEndpoint.HandleAsync:53] => Returned 1 accounts

13:21:17 [Error] [LogManager.DbContextLogger:36] => fail: 08/21/2024 13:21:17.997 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Failed executing DbCommand (3ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "d"."Id", "d"."CreatedAt", "d"."DownloadStatus", "d"."FullTitle", "d"."Key", "d"."PlexLibraryId", "d"."PlexServerId", "d"."Title", "d"."Year", "p"."Id", "p"."CreatedAt", "p"."Device", "p"."DnsRebindingProtection", "p"."Home", "p"."HttpsRequired", "p"."IsEnabled", "p"."LastSeenAt", "p"."MachineIdentifier", "p"."Name", "p"."NatLoopbackSupported", "p"."Owned", "p"."OwnerId", "p"."Platform", "p"."PlatformVersion", "p"."PlexServerOwnerUsername", "p"."PreferredConnectionId", "p"."Presence", "p"."Product", "p"."ProductVersion", "p"."Provides", "p"."PublicAddress", "p"."PublicAddressMatches", "p"."Relay", "p"."ServerFixApplyDNSFix", "p"."Synced", "p0"."Id", "p0"."CreatedAt", "p0"."DefaultDestinationId", "p0"."Key", "p0"."MetaData", "p0"."PlexServerId", "p0"."ScannedAt", "p0"."SyncedAt", "p0"."Title", "p0"."Type", "p0"."UpdatedAt", "p0"."Uuid", "t"."Id", "t"."CreatedAt", "t"."DownloadStatus", "t"."FullTitle", "t"."Key", "t"."PlexLibraryId", "t"."PlexServerId", "t"."Title", "t"."DataReceived", "t"."DataTotal", "t"."DirectoryMeta", "t"."DownloadSpeed", "t"."FileLocationUrl", "t"."FileName", "t"."FileTransferSpeed", "t"."Percentage", "t"."Quality", "t"."ParentId", "t"."Id0", "t"."CreatedAt0", "t"."Device", "t"."DnsRebindingProtection", "t"."Home", "t"."HttpsRequired", "t"."IsEnabled", "t"."LastSeenAt", "t"."MachineIdentifier", "t"."Name", "t"."NatLoopbackSupported", "t"."Owned", "t"."OwnerId", "t"."Platform", "t"."PlatformVersion", "t"."PlexServerOwnerUsername", "t"."PreferredConnectionId", "t"."Presence", "t"."Product", "t"."ProductVersion", "t"."Provides", "t"."PublicAddress", "t"."PublicAddressMatches", "t"."Relay", "t"."ServerFixApplyDNSFix", "t"."Synced", "t"."Id1", "t"."CreatedAt1", "t"."DefaultDestinationId", "t"."Key0", "t"."MetaData", "t"."PlexServerId0", "t"."ScannedAt", "t"."SyncedAt", "t"."Title0", "t"."Type", "t"."UpdatedAt", "t"."Uuid"
      FROM "DownloadTaskMovie" AS "d"
      INNER JOIN "PlexServers" AS "p" ON "d"."PlexServerId" = "p"."Id"
      INNER JOIN "PlexLibraries" AS "p0" ON "d"."PlexLibraryId" = "p0"."Id"
      LEFT JOIN (
          SELECT "d0"."Id", "d0"."CreatedAt", "d0"."DownloadStatus", "d0"."FullTitle", "d0"."Key", "d0"."PlexLibraryId", "d0"."PlexServerId", "d0"."Title", "d0"."DataReceived", "d0"."DataTotal", "d0"."DirectoryMeta", "d0"."DownloadSpeed", "d0"."FileLocationUrl", "d0"."FileName", "d0"."FileTransferSpeed", "d0"."Percentage", "d0"."Quality", "d0"."ParentId", "p1"."Id" AS "Id0", "p1"."CreatedAt" AS "CreatedAt0", "p1"."Device", "p1"."DnsRebindingProtection", "p1"."Home", "p1"."HttpsRequired", "p1"."IsEnabled", "p1"."LastSeenAt", "p1"."MachineIdentifier", "p1"."Name", "p1"."NatLoopbackSupported", "p1"."Owned", "p1"."OwnerId", "p1"."Platform", "p1"."PlatformVersion", "p1"."PlexServerOwnerUsername", "p1"."PreferredConnectionId", "p1"."Presence", "p1"."Product", "p1"."ProductVersion", "p1"."Provides", "p1"."PublicAddress", "p1"."PublicAddressMatches", "p1"."Relay", "p1"."ServerFixApplyDNSFix", "p1"."Synced", "p2"."Id" AS "Id1", "p2"."CreatedAt" AS "CreatedAt1", "p2"."DefaultDestinationId", "p2"."Key" AS "Key0", "p2"."MetaData", "p2"."PlexServerId" AS "PlexServerId0", "p2"."ScannedAt", "p2"."SyncedAt", "p2"."Title" AS "Title0", "p2"."Type", "p2"."UpdatedAt", "p2"."Uuid"
          FROM "DownloadTaskMovieFile" AS "d0"
          INNER JOIN "PlexServers" AS "p1" ON "d0"."PlexServerId" = "p1"."Id"
          INNER JOIN "PlexLibraries" AS "p2" ON "d0"."PlexLibraryId" = "p2"."Id"
      ) AS "t" ON "d"."Id" = "t"."ParentId"
      ORDER BY "d"."Id", "p"."Id", "p0"."Id", "t"."CreatedAt", "t"."Id", "t"."Id0"

13:21:18 [Error] [LogManager.DbContextLogger:36] => fail: 08/21/2024 13:21:18.004 CoreEventId.QueryIterationFailed[10100] (Microsoft.EntityFrameworkCore.Query) 
      An exception occurred while iterating over the results of a query for context type 'PlexRipper.Data.PlexRipperDbContext'.
      Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
         at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
         at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

13:21:18 [Error] [Microsoft.Kestrel:0] => Connection id "0HN61TR3FPTK4", Request id "0HN61TR3FPTK4:00000001": An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 11: 'database disk image is malformed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Data.Contracts.DbContextExtensions.GetAllDownloadTasksByServerAsync(IPlexRipperDbContext dbContext, Int32 plexServerId, Boolean asTracking, CancellationToken cancellationToken) in /src/src/Data.Contracts/Extensions/DbContext/DbContextExtensions.DownloadTasks.cs:line 223
   at PlexRipper.Application.GetAllDownloadTasksEndpoint.HandleAsync(CancellationToken ct) in /src/src/Application/PlexDownloads/GetAll/GetAllDownloadTasksEndpoint.cs:line 30
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

13:21:37 [Information] [ConfigManager.SaveConfig:135] => Saving user config settings now

13:21:37 [Information] [ConfigManager.SaveConfig:143] => UserSettings were saved successfully!
```

**Comment by JasonLandbridge** [comment]
@Hoopes80 Hey, thank you very much for my first donation ever!

This does seem like an hardware issue, can you confirm that the `/config` directory is on a working drive? Preferably SSD

Edit: And is this all the logs that are shown when you boot up PlexRipper?

**Comment by Hoopes80** [comment]
Crazy. It's the best program ever. You deserve more donations.

Yep it is. Samsung EVO ssd. Brand new. I uninstalled it and reinstalled and it started working again.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by Hoopes80** [comment]
> @Hoopes80 Hey, thank you very much for my first donation ever!
> 
> This does seem like an hardware issue, can you confirm that the `/config` directory is on a working drive? Preferably SSD
> 
> Edit: And is this all the logs that are shown when you boot up PlexRipper?
> 

Crazy. It's the best program ever. You deserve more donations.

Yep it is. Samsung EVO ssd. Brand new. I uninstalled it and reinstalled and it started working again.

**Comment by Hoopes80** [comment]
I'm assuming there's no version of this that can be ran on Windows?

**Comment by JasonLandbridge** [comment]
Yes there is, although it's a length process in setting it up: https://www.plexripper.rocks/guides/installation/windows
