### ISSUE TITLE
[BUG] - Unable to get starting with docker compose

### ISSUE THREAD

**Issue by talormanda** [PlexRipper/PlexRipper#343]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

v0.21.0

### Platform

Other (Specify in description)

### Browsers

Google Chrome

### Description

Page never loads. Log has errors.
Here is my config:

```
version: '3.4'
services:
  plexripper:
    container_name: PlexRipper
    image: plexripper/plexripper
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      # Web UI & Web API
      - '7000:7000'
    restart: unless-stopped
    volumes:
      - /mnt/PROJECTS/PlexRipperCache/Config:/Config
      - /mnt/PROJECTS/PlexRipperCache/Downloads:/Downloads
      - /mnt/PROJECTS/PlexRipperCache/Movies:/Movies
      - /mnt/PROJECTS/PlexRipperCache/TvShows:/TvShows
```

### Reproduction steps

```bash
n/a
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

```bash
23:08:57 [Error] [PlexRipperDbContext.Setup:214] => Failed to migrate the database or the database is corrupted
23:08:57 [Error] [PlexRipperDbContext.Setup:215] => Exception
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PlexRipper.Data.PlexRipperDbContext.Setup() in /src/src/Data/PlexRipperDbContext.cs:line 209
23:08:57 [Information] [PlexRipperDbContext.ResetDatabase:240] => Resetting PlexRipper database now
23:08:57 [Information] [PlexRipperDbContext.BackUpDatabase:258] => Attempting to back-up the PlexRipper database
23:08:57 [Information] [PlexRipperDbContext.BackUpDatabase:282] => Successfully copied "/Config/PlexRipperDB.db" to back-up location"/Config/Database BackUp/24-08-25_11-08/PlexRipperDB.db"
23:08:57 [Warning] [PlexRipperDbContext.BackUpDatabase:303] => Could not find: /Config/PlexRipperDB.db-shm to backup
23:08:57 [Warning] [PlexRipperDbContext.BackUpDatabase:303] => Could not find: /Config/PlexRipperDB.db-wal to backup
23:09:27 [Error] [LogManager.DbContextLogger:36] => fail: 08/25/2024 23:09:27.794 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Failed executing DbCommand (30,142ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      PRAGMA journal_mode = 'wal';
23:09:27 [Fatal] [PlexRipperDbContext.ResetDatabase:249] => Failed to reset database!
23:09:27 [Fatal] [PlexRipperDbContext.ResetDatabase:250] => TO FIX THIS: DELETE DATABASE MANUALLY FROM THE CONFIG DIRECTORY
23:09:27 [Fatal] [PlexRipperDbContext.ResetDatabase:251] => SQLite Error 5: 'database is locked'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PlexRipper.Data.PlexRipperDbContext.ResetDatabase() in /src/src/Data/PlexRipperDbContext.cs:line 244
23:09:27 [Fatal] [Program.Main:34] => SQLite Error 5: 'database is locked'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PlexRipper.Data.PlexRipperDbContext.ResetDatabase() in /src/src/Data/PlexRipperDbContext.cs:line 244
   at PlexRipper.Data.PlexRipperDbContext.Setup() in /src/src/Data/PlexRipperDbContext.cs:line 216
   at PlexRipper.WebAPI.Startup.ConfigureDatabase(WebApplicationBuilder builder) in /src/src/WebAPI/Startup.cs:line 189
   at PlexRipper.WebAPI.Program.Main(String[] args) in /src/src/WebAPI/Program.cs:line 20
23:09:28 [Information] [LogManager.SetupLogging:44] => Logging level set to Verbose
23:09:28 [Information] [Program.Main:16] => Currently running on Linux
23:09:28 [Information] [PlexRipperDbContext.Setup:202] => Setting up the PlexRipper database
23:09:30 [Information] [PlexRipperDbContext.Setup:208] => Attempting to migrate database
23:10:00 [Error] [LogManager.DbContextLogger:36] => fail: 08/25/2024 23:10:00.545 RelationalEventId.CommandError[20102] (Microsoft.EntityFrameworkCore.Database.Command) 
      Failed executing DbCommand (30,135ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      CREATE TABLE "__EFMigrationsHistory" (
          "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
          "ProductVersion" TEXT NOT NULL
      );
23:10:00 [Error] [PlexRipperDbContext.Setup:214] => Failed to migrate the database or the database is corrupted
23:10:00 [Error] [PlexRipperDbContext.Setup:215] => Exception
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteNonQuery(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PlexRipper.Data.PlexRipperDbContext.Setup() in /src/src/Data/PlexRipperDbContext.cs:line 209
23:10:00 [Information] [PlexRipperDbContext.ResetDatabase:240] => Resetting PlexRipper database now
23:10:00 [Information] [PlexRipperDbContext.BackUpDatabase:258] => Attempting to back-up the PlexRipper database
23:10:00 [Information] [PlexRipperDbContext.BackUpDatabase:282] => Successfully copied "/Config/PlexRipperDB.db" to back-up location"/Config/Database BackUp/24-08-25_11-10/PlexRipperDB.db"
23:10:00 [Warning] [PlexRipperDbContext.BackUpDatabase:303] => Could not find: /Config/PlexRipperDB.db-shm to backup
23:10:00 [Warning] [PlexRipperDbContext.BackUpDatabase:303] => Could not find: /Config/PlexRipperDB.db-wal to backup
```

**Comment by talormanda** [comment]
For some reason it freaked out when I had the config folder set to my NAS as a symlink. I made it local and it worked.

**Comment by talormanda** [comment]
.
