### ISSUE TITLE
[BUG] - Multiple Servers under account seems to break

### ISSUE THREAD

**Issue by crzykidd** [PlexRipper/PlexRipper#357]
### Checks

- [X] I have searched the existing issues for a similar bug and it does not exist!

### PlexRipper version

V0.23.2

### Platform

Linux

### Browsers

Google Chrome

### Description

I have 2 servers under my account.   They both show up with the House next to them.   However both show the same libraries, and the libraries aren't indexing, DC should have different libraries than Archive.

### Reproduction steps

```bash
add an account with 2 primary servers.
```

### Screenshots

```bash
![Screen Shot of both servers](https://imgur.com/a/WeOIHyM)
```

### Logs

```bash
23:59:34 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=27000&X-Plex-Container-Size=1000

23:59:35 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=28000&X-Plex-Container-Size=1000

23:59:37 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=29000&X-Plex-Container-Size=1000

23:59:38 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=30000&X-Plex-Container-Size=1000

23:59:39 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=31000&X-Plex-Container-Size=1000

23:59:40 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=32000&X-Plex-Container-Size=1000

23:59:41 [Debug] [PlexApiClient.SendAsync:90] => Request: http://***MASKED***/library/sections/2/all?includeGuids=1&type=4&includeMeta=0&X-Plex-Container-Start=33000&X-Plex-Container-Size=1000

23:59:42 [Information] [PlexApiService.SyncMedia:410] => Finished getting 33531 media items from library with name ***MASKED***  

23:59:43 [Error] [ExceptionLoggingHandler.Handle:26] => An exception of type "System.ArgumentOutOfRangeException" happened when handling request of type "PlexRipper.Application.RefreshLibraryMediaCommand"

23:59:43 [Error] [ExceptionLoggingHandler.Handle:31] => Exception
System.ArgumentOutOfRangeException: Valid values are between -62135596800 and 253402300799, inclusive. (Parameter 'seconds')
   at System.DateTimeOffset.FromUnixTimeSeconds(Int64 seconds)
   at PlexRipper.PlexApi.PlexMetaDataMapper.ToPlexMedia(GetLibraryItemsMetadata source) in /src/src/PlexApi/Common/Mappers/PlexMetaDataMapper.cs:line 42
   at PlexRipper.PlexApi.PlexMetaDataMapper.ToPlexTvShowEpisode(GetLibraryItemsMetadata source) in /src/src/PlexApi/Common/Mappers/PlexMetaDataMapper.cs:line 34
   at System.Collections.Generic.List`1.ConvertAll[TOutput](Converter`2 converter)
   at PlexRipper.PlexApi.PlexMetaDataMapper.ToPlexTvShowEpisodes(List`1 source) in /src/src/PlexApi/Common/Mappers/PlexMetaDataMapper.cs:line 97
   at PlexRipper.PlexApi.PlexApiService.GetAllEpisodesAsync(PlexLibrary plexLibrary, Action`1 action, CancellationToken cancellationToken) in /src/src/PlexApi/PlexApiService.cs:line 119
   at PlexRipper.Application.RefreshLibraryMediaCommandHandler.RefreshPlexTvShowLibrary(PlexLibrary plexLibrary) in /src/src/Application/PlexLibraries/RefreshLibraryMedia/RefreshLibraryMediaCommand.cs:line 121
   at PlexRipper.Application.RefreshLibraryMediaCommandHandler.Handle(RefreshLibraryMediaCommand command, CancellationToken cancellationToken) in /src/src/Application/PlexLibraries/RefreshLibraryMedia/RefreshLibraryMediaCommand.cs:line 93
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, RequestHandlerDelegate`1 next, CancellationToken cancellationToken)
```

**Comment by JasonLandbridge** [comment]
Hi, could you send the account token to plexripper@protonmail.com so i can take a look?
